name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# ───────────────────────── Build ─────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ---------- Backend ----------
      - name: Install backend dependencies
        run: npm ci          # repo-root holds backend package.json

      # ---------- Frontend ----------
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React app
        working-directory: frontend
        env:
          CI: false
        run: npm run build

# ──────────────────────── Deploy ────────────────────────
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # need checkout to reference repo files later
      - uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update -y && sudo apt-get install -y sshpass

      - name: Deploy to droplet
        env:
          SSH_HOST:      ${{ secrets.SSH_HOST }}      # droplet IP
          SSH_USERNAME:  ${{ secrets.SSH_USERNAME }}  # root
          SSH_KEY:       ${{ secrets.SSH_KEY }}       # droplet password
        run: |
          sshpass -p "$SSH_KEY" ssh -o StrictHostKeyChecking=no \
            ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          set -e

          # v1. Backend update on droplet
          cd /var/karawhyteServer          # path where you cloned the repo on the VM
          git pull origin main
          npm ci
          pm2 restart express-server || pm2 start server.js --name express-server
          pm2 save

          # 2. Frontend rebuild on droplet
          cd /var/karateServer/frontend
          npm ci
          npm run build

          # 3. Deploy static bundle for Nginx
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html
          EOF
        
